#!/usr/bin/env python3
"""FW-CADIS weight-window spike for the 0.2 test run.

Question: do FW-CADIS weight windows generated by a random-ray multigroup pass
and applied to the continuous-energy OpenMC model cut the sampling error of the
magnet peak and the vessel/magnet spectra, measured against the analog run of
the same model (docs/DEMO_ROADMAP.md, "Magnet peak with FW-CADIS weight
windows" and "Decisions for 0.2")?

The model is the FARIS adapter's own: this script imports
integrations/openmc/reactor_transport.py and calls its check_data_identity()
and compose() on a FARIS request input.json, so geometry, materials, source and
settings are the adapter's, not a reimplementation. The adapter is unchanged.
It then replaces the tallies with the spike's own and turns photon transport
off (neutron-only comparison; the adapter's heating responses are not part of
this question).

Subcommands (each writes into a fresh subdirectory of --work-dir):

  build      export the adapter model and the spike model, report the tallies
  mgxs-plan  write the multigroup + random-ray + weight-window configuration as
             JSON (nothing is executed)
  generate   run MGXS generation, the random-ray solve and write
             weight_windows.h5 (needs --i-have-the-cpu)
  compare    run the analog and the weight-windowed continuous-energy model and
             report per-bin relative error, variance of the variance and figure
             of merit (needs --i-have-the-cpu)

`generate` and `compare` run OpenMC for a long time on many cores; they refuse
to start without --i-have-the-cpu.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import math
import os
from pathlib import Path
import re
import subprocess
import sys
import time
import warnings

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import reactor_transport as RT  # noqa: E402  (the adapter; compose() builds the model)

# Deep-copying a model for the plan duplicates filter ids; the copies are never exported.
warnings.filterwarnings("ignore", message="Another .* instance already exists with id=")

SCHEMA = "faris-fwcadis-spike/v0.1"
OPENMC_VERSION = "0.15.3"
ACTINV_709G = Path("/home/connoravila/Documents/actinv/actinv-data/v1.1.0/activation/tendl-2025-neutron-709g.npz")

# Peak-magnet mesh. Radial extent comes from the magnets layer of the scenario.
# The transverse extent (y and z) is the finite-port prism of the paired port
# case (port-reference input.json: bounds y and z in [-0.15, 0.15] m, centred
# on toroidal angle 0), used for the port-free control too so that both cases
# are measured over the same footprint behind where the port goes.
PORT_HALF_WIDTH_M = 0.15
OUTBOARD_DIMS = (8, 10, 10)  # 2 cm radial x 3 cm x 3 cm bins
FAST_FLUX_LOWER_EV = 1.0e5  # E > 0.1 MeV
FAST_FLUX_UPPER_EV = RT.SPECTRUM_EDGES_EV[-1]
SPECTRUM_COMPONENTS = ("vessel", "magnets")

# Weight-window mesh: one Cartesian mesh over the whole torus, 0.2 m cells.
# Not tuned; the radial build is 1.2 m so this resolves the shield and
# blanket coarsely. Revisit after the test run.
WW_MARGIN_M = 0.02
WW_CELL_M = 0.2

# Random-ray group structure (eV, ascending; OpenMC numbers group 1 as the
# highest energy). A cut at 0.1 MeV matches the fast-flux definition, and
# 13.5-14.5 MeV isolates the 14.1 MeV source in one group. Top edge 20 MeV is
# the top of the FENDL neutron data.
RR_GROUP_EDGES_EV = [
    1.0e-5, 0.1, 1.0, 10.0, 100.0, 1.0e3, 1.0e4, 3.0e4, 1.0e5, 3.0e5, 5.0e5,
    1.0e6, 1.5e6, 2.0e6, 3.0e6, 4.0e6, 5.0e6, 6.0e6, 8.0e6, 1.0e7, 1.2e7,
    1.35e7, 1.45e7, 2.0e7,
]

PLAN_DEFAULTS = {
    # stochastic_slab, not material_wise: material_wise runs the real source
    # through the real model and tallies cross sections only where particles
    # go, so the copper magnets behind a metre of shield would get empty or
    # noisy data (the roadmap's reason for FW-CADIS in the first place);
    # stochastic_slab gives every material data (model.py:1887-1996, doc text
    # at 1895-1903 and 2006-2014).
    "mgxs_method": "stochastic_slab",
    # P0 transport correction: the shield is 67 % hydrogen and the blanket
    # has Li/Be/F, whose forward-peaked scattering the isotropic random-ray
    # solver otherwise ignores. It yields negative in-group elements, handled
    # by diagonal stabilization (settings.py:196-205).
    "mgxs_correction": "P0",
    "mgxs_nparticles": 20000,
    "rays": 200000,
    "batches": 300,
    "inactive": 100,
    "distance_inactive_cm": 500.0,
    "distance_active_cm": 2500.0,
    # Flat source: the solver warns linear sources give poor FW-CADIS windows
    # when an overlaid mesh subdivides source regions (libopenmc.so string;
    # the C++ is not in site-packages).
    "source_shape": "flat",
    "volume_estimator": "hybrid",
    "diagonal_stabilization_rho": 1.0,
    "sample_method": "prng",
    "seed": 81150099,
}


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def fresh_dir(path: Path) -> Path:
    path = path.expanduser().resolve()
    require(not path.exists(), f"{path} exists; refusing to overwrite")
    path.mkdir(parents=True)
    return path


# --------------------------------------------------------------------------
# Pure helpers (no OpenMC needed)

def load_709_bounds(path: Path = ACTINV_709G):
    """The 710 fispact-709 group boundaries in eV, ascending."""
    import numpy as np
    bounds = np.load(path)["bounds"]
    require(bounds.shape == (710,), f"expected 710 bounds, got {bounds.shape}")
    require(bool(np.all(np.diff(bounds) > 0)), "709-group bounds are not strictly increasing")
    return bounds


def select_variant(inp: dict) -> dict:
    variant = next((v for v in inp["manifest"]["variants"] if v["id"] == inp["physics"]["variant_id"]), None)
    require(variant is not None, "physics variant missing from manifest")
    return variant


def component(variant: dict, component_id: str) -> dict:
    found = next((c for c in variant["components"] if c["id"] == component_id), None)
    require(found is not None, f"variant has no component {component_id}")
    return found


def r9(values: list[float]) -> list[float]:
    """Round away binary noise (1e-9 m) so extents read as the numbers they mean."""
    return [round(float(v), 9) for v in values]


def peak_mesh_extents(manifest: dict, variant: dict, dims: tuple[int, int, int] = OUTBOARD_DIMS) -> dict:
    """Outboard peak mesh behind the port and the matching inboard slab, in metres.

    The torus axis is y and the port is centred on toroidal angle 0 (the +x
    axis), so on the midplane the magnets layer spans R0 + [a, b] outboard and
    R0 - [b, a] inboard (a, b = inner and outer minor radius of the magnets).
    Transverse extent: the penetration prism's y and z bounds if the manifest
    has one, otherwise +-PORT_HALF_WIDTH_M (see the constant). The mesh is
    axis-aligned, so over the transverse half-width w the magnets' curved
    surfaces lie within R0 + a - 0.0005 .. R0 + b (for w = 0.15 m): the box
    slightly over-covers the layer by under 1 mm and is otherwise inside it.
    """
    R = float(manifest["major_radius_m"])
    magnets = component(variant, "magnets")
    a, b = float(magnets["inner_minor_radius_m"]), float(magnets["outer_minor_radius_m"])
    require(0.0 < a < b < R, "magnets layer radii must satisfy 0 < inner < outer < R0")
    penetration = manifest.get("penetration")
    if penetration is not None:
        bounds = penetration["bounds_m"]
        lo, hi = bounds["minimum_xyz_m"], bounds["maximum_xyz_m"]
        y, z = [float(lo[1]), float(hi[1])], [float(lo[2]), float(hi[2])]
        source = "penetration bounds_m y,z"
    else:
        y = z = [-PORT_HALF_WIDTH_M, PORT_HALF_WIDTH_M]
        source = f"+-{PORT_HALF_WIDTH_M} m (port-reference prism half width)"
    return {
        "outboard": {"lower_left_m": r9([R + a, y[0], z[0]]), "upper_right_m": r9([R + b, y[1], z[1]]), "dimensions": list(dims)},
        "inboard": {"lower_left_m": r9([R - b, y[0], z[0]]), "upper_right_m": r9([R - a, y[1], z[1]]), "dimensions": list(dims)},
        "derivation": {
            "major_radius_m": R,
            "magnets_inner_minor_radius_m": a,
            "magnets_outer_minor_radius_m": b,
            "transverse_extent_source": source,
            "toroidal_angle_of_port_centre_rad": 0.0,
        },
    }


def ww_mesh_extents(manifest: dict, variant: dict, cell_m: float = WW_CELL_M) -> dict:
    """Weight-window mesh: the whole torus, so windows exist wherever a particle goes."""
    R = float(manifest["major_radius_m"])
    outer = float(variant["components"][-1]["outer_minor_radius_m"])
    half_xz = math.ceil((R + outer + WW_MARGIN_M) / cell_m) * cell_m
    half_y = math.ceil((outer + WW_MARGIN_M) / cell_m) * cell_m
    dims = [round(2 * half_xz / cell_m), round(2 * half_y / cell_m), round(2 * half_xz / cell_m)]
    return {"lower_left_m": r9([-half_xz, -half_y, -half_xz]), "upper_right_m": r9([half_xz, half_y, half_xz]), "dimensions": dims, "cell_m": cell_m}


def source_group(edges_ev: list[float], energy_ev: float) -> dict:
    """The one random-ray group holding the source energy. Group 1 is the highest energy."""
    require(edges_ev[0] < energy_ev < edges_ev[-1], "source energy outside the group structure")
    n = len(edges_ev) - 1
    for i in range(n):
        if edges_ev[i] <= energy_ev < edges_ev[i + 1]:
            return {"group_index_1_based_high_to_low": n - i, "lower_ev": edges_ev[i], "upper_ev": edges_ev[i + 1], "source_energy_ev": energy_ev}
    raise RuntimeError("unreachable")


def variance_of_variance(batch_values):
    """Per-bin VOV from batch values, shape (n_batches, n_bins): sum d^4 / (sum d^2)^2 - 1/n.

    Bins with no scores (zero denominator) give NaN.
    """
    import numpy as np
    x = np.asarray(batch_values, dtype=float)
    n = x.shape[0]
    d = x - x.mean(axis=0)
    s2 = (d ** 2).sum(axis=0)
    s4 = (d ** 4).sum(axis=0)
    with np.errstate(divide="ignore", invalid="ignore"):
        vov = s4 / s2 ** 2 - 1.0 / n
    return np.where(s2 > 0, vov, np.nan)


# --------------------------------------------------------------------------
# Model construction (reuses the adapter)

def import_openmc():
    import openmc
    require(openmc.__version__ == OPENMC_VERSION, f"expected OpenMC {OPENMC_VERSION}, got {openmc.__version__}")
    return openmc


def adapter_model(inp: dict, adapter_dir: Path, openmc):
    """The adapter's compose(), called exactly as reactor_transport.main() does."""
    xml = Path(inp["cross_sections"]).expanduser().resolve(strict=True)
    os.environ["OPENMC_CROSS_SECTIONS"] = str(xml)
    inp = copy.deepcopy(inp)
    # A port request would sample 1M points in Python for volumes this spike
    # never uses; the adapter's minimum is enough.
    if inp["manifest"].get("penetration") is not None:
        inp["penetration_volume_samples"] = 100_000
    coupled = any(r["score"]["kind"] == "heating" for r in inp["request"]["responses"])
    _, _, _, runtime_temperature, _, photon_physics = RT.check_data_identity(inp["physics"], xml, openmc, coupled)
    result = RT.compose(inp, adapter_dir, openmc, runtime_temperature, photon_physics)
    keys = ("model", "response_by_tally", "mesh_tally", "mesh_defs", "volumes_cm3", "volume_se_cm3", "whole_cm3", "mesh_bin_cm3",
            "component_cells", "spectrum_tallies", "plasma", "mesh_index_audit", "penetration_volume_audit", "geometry_audit", "region_volumes_cm3")
    return dict(zip(keys, result)), inp


def regular_mesh(openmc, spec: dict, name: str):
    mesh = openmc.RegularMesh(name=name)
    mesh.dimension = tuple(spec["dimensions"])
    mesh.lower_left = [100.0 * v for v in spec["lower_left_m"]]
    mesh.upper_right = [100.0 * v for v in spec["upper_right_m"]]
    return mesh


def build_spike(inp: dict, work: Path, openmc, dims: tuple[int, int, int] = OUTBOARD_DIMS) -> dict:
    """Adapter model plus the spike's tallies. Exports adapter and spike XML."""
    parts, inp = adapter_model(inp, work / "adapter-export", openmc)
    model = parts["model"]
    manifest = inp["manifest"]
    variant = select_variant(inp)
    cells = parts["component_cells"]
    for cid in SPECTRUM_COMPONENTS:
        require(cid in cells, f"scenario has no component {cid}")
    extents = peak_mesh_extents(manifest, variant, dims)
    bounds = load_709_bounds()
    energy_fast = openmc.EnergyFilter([FAST_FLUX_LOWER_EV, FAST_FLUX_UPPER_EV])
    neutron = openmc.ParticleFilter("neutron")
    tallies = openmc.Tallies()
    meshes = {}

    def add(name, filters, scores=("flux",)):
        tally = openmc.Tally(name=name)
        tally.filters = filters
        tally.scores = list(scores)
        tally.estimator = "tracklength"
        tallies.append(tally)
        return tally

    for side in ("outboard", "inboard"):
        spec = extents[side]
        fine = regular_mesh(openmc, spec, f"peak-{side}")
        meshes[side] = fine
        add(f"peak-{side}-fast-flux", [openmc.MeshFilter(fine), energy_fast, neutron])
        whole = regular_mesh(openmc, {**spec, "dimensions": [1, 1, 1]}, f"peak-{side}-mean")
        add(f"peak-{side}-fast-flux-mean", [openmc.MeshFilter(whole), energy_fast, neutron])
    spectrum_filter = openmc.EnergyFilter(bounds)
    for cid in SPECTRUM_COMPONENTS:
        add(f"spectrum-709-{cid}", [openmc.CellFilter(cells[cid]), neutron, spectrum_filter])
        add(f"fast-flux-{cid}", [openmc.CellFilter(cells[cid]), energy_fast, neutron])
    model.tallies = tallies
    settings = model.settings
    settings.photon_transport = False
    settings.statepoint = {}
    spike_dir = work / "spike-export"
    spike_dir.mkdir()
    model.export_to_xml(directory=str(spike_dir))
    return {"model": model, "parts": parts, "inp": inp, "extents": extents, "meshes": meshes, "tally_names": [t.name for t in tallies],
            "adapter_dir": work / "adapter-export", "spike_dir": spike_dir, "variant": variant}


def xml_hashes(directory: Path) -> dict[str, str]:
    return {p.name: sha256(p) for p in sorted(directory.glob("*.xml"))}


def void_report(parts: dict) -> dict:
    """Random ray needs void as a null-filled cell; the adapter already does this."""
    cells = parts["model"].geometry.get_all_cells().values()
    void_cells = sorted(c.name for c in cells if c.fill is None)
    require(void_cells, "no null-filled void cells found")
    require(not any(m.density == 0.0 for m in parts["model"].materials), "a zero-density material is present")
    return {"adapter_source": "reactor_transport.compose(): void recipe -> materials[id] = None, cells filled with None",
            "null_filled_cells": void_cells}


# --------------------------------------------------------------------------
# Multigroup / random-ray configuration

def rr_tallies(openmc, build: dict, edges_ev: list[float]):
    """Flux-only tallies that define the FW-CADIS objective.

    Random ray accepts only flux/total/fission/nu-fission/events scores and
    cell/cell_instance/distribcell/energy/material/mesh/universe filters, so
    the particle filter of the continuous-energy tallies is dropped (strings in
    libopenmc.so; the solver source is not shipped). Energy filters use group
    edges: the fast-flux filter is [0.1 MeV, 20 MeV], the component filters
    the whole structure.
    """
    cells = build["parts"]["component_cells"]
    fast = openmc.EnergyFilter([FAST_FLUX_LOWER_EV, edges_ev[-1]])
    full = openmc.EnergyFilter(edges_ev)
    tallies = openmc.Tallies()
    for side in ("outboard", "inboard"):
        t = openmc.Tally(name=f"rr-peak-{side}-fast-flux")
        t.filters = [openmc.MeshFilter(build["meshes"][side]), fast]
        t.scores = ["flux"]
        tallies.append(t)
    for cid in SPECTRUM_COMPONENTS:
        t = openmc.Tally(name=f"rr-{cid}-flux")
        t.filters = [openmc.CellFilter(cells[cid]), full]
        t.scores = ["flux"]
        tallies.append(t)
    return tallies


def configure_random_ray(openmc, model, ww_mesh, params: dict, edges_ev: list[float], rr_tally_set, ray_box_cm, subdivide_domains):
    """Put the random-ray and FW-CADIS settings on a (multigroup) model.

    Every key is one OpenMC 0.15.3 validates in Settings.random_ray
    (settings.py:1302-1347, documented 180-225) or a plain Settings attribute.
    """
    settings = model.settings
    settings.energy_mode = "multi-group"
    settings.run_mode = "fixed source"
    settings.photon_transport = False
    settings.batches = int(params["batches"])
    settings.inactive = int(params["inactive"])
    settings.particles = int(params["rays"])  # rays per batch in random-ray mode (model.py:2233)
    settings.seed = int(params["seed"])
    settings.statepoint = {}
    lower, upper = ray_box_cm
    settings.random_ray = {
        "distance_inactive": float(params["distance_inactive_cm"]),
        "distance_active": float(params["distance_active_cm"]),
        "ray_source": openmc.IndependentSource(space=openmc.stats.Box(lower, upper)),
        "volume_estimator": params["volume_estimator"],
        "source_shape": params["source_shape"],
        "adjoint": False,  # FW-CADIS runs its own forward then adjoint solve; the flag is for a pure adjoint run
        "sample_method": params["sample_method"],
        "diagonal_stabilization_rho": float(params["diagonal_stabilization_rho"]),
        "source_region_meshes": [(ww_mesh, subdivide_domains)],
    }
    model.tallies = rr_tally_set
    settings.weight_window_generators = [openmc.WeightWindowGenerator(
        mesh=ww_mesh, energy_bounds=list(edges_ev), particle_type="neutron", method="fw_cadis",
        max_realizations=int(params["batches"]),  # as in the OpenMC random-ray example: update once, at the end
    )]


def subdivision_domains(model):
    """Non-void materials plus null-filled cells: disjoint, so no source region gets two meshes."""
    domains = list(model.materials)
    domains += [c for c in model.geometry.root_universe.cells.values() if c.fill is None]
    return domains


def describe_random_ray(model) -> dict:
    s = model.settings
    rr = s.random_ray
    box = rr["ray_source"].space
    wwg = s.weight_window_generators[0]
    mesh, domains = rr["source_region_meshes"][0]
    return {
        "energy_mode": s.energy_mode,
        "run_mode": s.run_mode,
        "batches": s.batches,
        "inactive": s.inactive,
        "rays_per_batch_settings_particles": s.particles,
        "photon_transport": s.photon_transport,
        "random_ray": {
            "adjoint": rr["adjoint"],
            "distance_inactive_cm": rr["distance_inactive"],
            "distance_active_cm": rr["distance_active"],
            "ray_source_box_cm": {"lower_left": [float(v) for v in box.lower_left], "upper_right": [float(v) for v in box.upper_right]},
            "volume_estimator": rr["volume_estimator"],
            "source_shape": rr["source_shape"],
            "sample_method": rr["sample_method"],
            "diagonal_stabilization_rho": rr["diagonal_stabilization_rho"],
            "source_region_meshes": [{"mesh_dimension": [int(v) for v in mesh.dimension], "lower_left_cm": [float(v) for v in mesh.lower_left],
                                      "upper_right_cm": [float(v) for v in mesh.upper_right], "domains": [type(d).__name__ + ":" + str(d.name) for d in domains]}],
        },
        "weight_window_generator": {
            "method": wwg.method,
            "particle_type": wwg.particle_type,
            "energy_bounds_ev": [float(v) for v in wwg.energy_bounds],
            "max_realizations": wwg.max_realizations,
            "update_interval": wwg.update_interval,
            "on_the_fly": wwg.on_the_fly,
            "update_parameters": wwg.update_parameters,
            "mesh_dimension": [int(v) for v in wwg.mesh.dimension],
        },
        "tallies": [{"name": t.name, "scores": t.scores, "filters": [type(f).__name__ for f in t.filters]} for t in model.tallies],
    }


CITATIONS = {
    "convert_to_multigroup": "openmc/model/model.py:2094-2174 (args method, groups, nparticles, overwrite_mgxs_library, mgxs_path, correction; method dispatch 2150-2162)",
    "mgxs_method_stochastic_slab": "openmc/model/model.py:1887-1996 (runs a stochastic slab sandwich of all materials; uniform-in-group discrete source 1933-1944)",
    "mgxs_method_material_wise": "openmc/model/model.py:1998-2092 (runs the real model and source; zero data where particles never score, doc 2006-2014)",
    "mgxs_correction": "openmc/model/model.py:2051-2060 (correction None -> 'total'; 'P0' -> 'nu-transport')",
    "convert_to_random_ray": "openmc/model/model.py:2176-2234 (needs multi-group 2201; bounding box 2216-2219 turns infinities into +-1 cm; skipped if random_ray already set 2196)",
    "random_ray_keys": "openmc/settings.py:1302-1347 setter (distance_active, distance_inactive, ray_source, volume_estimator, source_shape, volume_normalized_flux_tallies, adjoint, source_region_meshes, sample_method, diagonal_stabilization_rho); docs settings.py:180-225",
    "weight_window_generator": "openmc/weight_windows.py:485-553 (mesh, energy_bounds, particle_type, method in {'magic','fw_cadis'} at 599-610, max_realizations, update_interval, on_the_fly)",
    "weight_window_generators_setting": "openmc/settings.py:1289-1296",
    "weight_windows_file_and_on": "openmc/settings.py:1222-1228 (weight_windows_on), 1277-1286 (weight_windows_file), 1247-1254 (max_history_splits)",
    "random_ray_restrictions": "strings of lib/libopenmc.so (the C++ solver is not in site-packages): tally scores flux/total/fission/nu-fission/event only; filters cell/cell_instance/distribcell/energy/material/mesh/universe only; isotropic isothermal MGXS only; void = null-filled cell; source must be a discrete-energy isotropic IndependentSource constrained to a domain; 'FW-CADIS can only be run in random ray solver mode'",
}


def plan_document(inp: dict, build: dict, params: dict, openmc) -> dict:
    edges = RR_GROUP_EDGES_EV
    manifest = inp["manifest"]
    variant = build["variant"]
    ww = ww_mesh_extents(manifest, variant)
    ww_mesh = regular_mesh(openmc, ww, "fw-cadis-ww-mesh")
    ray_box = ([100.0 * v for v in ww["lower_left_m"]], [100.0 * v for v in ww["upper_right_m"]])
    rr_model = copy.deepcopy(build["model"])
    # Rebuild the objective tallies against the copy's own cells and meshes.
    rr_build = {"parts": {"component_cells": {cid: next(c for c in rr_model.geometry.get_all_cells().values() if c.name == cid and c.fill is not None) for cid in SPECTRUM_COMPONENTS}},
                "meshes": {side: regular_mesh(openmc, build["extents"][side], f"peak-{side}") for side in ("outboard", "inboard")}}
    # What convert_to_random_ray() would pick, for the record (it needs an MG model).
    probe = copy.deepcopy(rr_model)
    probe.settings.energy_mode = "multi-group"
    probe.settings.random_ray = {}
    probe.convert_to_random_ray()
    probe_rr = probe.settings.random_ray
    probe_box = probe_rr["ray_source"].space
    configure_random_ray(openmc, rr_model, ww_mesh, params, edges, rr_tallies(openmc, rr_build, edges), ray_box, subdivision_domains(rr_model))
    energy = float(inp["request"]["source"]["neutron_energy_ev"])
    return {
        "schema_version": SCHEMA,
        "kind": "mgxs-plan",
        "executed": False,
        "openmc_version": openmc.__version__,
        "request": {"scenario_id": manifest["scenario_id"], "variant_id": inp["physics"]["variant_id"]},
        "convert_to_multigroup": {
            "call": "Model.convert_to_multigroup(method, groups, nparticles, overwrite_mgxs_library, mgxs_path, correction)",
            "method": params["mgxs_method"],
            "groups_ev_ascending": edges,
            "n_groups": len(edges) - 1,
            "nparticles": params["mgxs_nparticles"],
            "correction": params["mgxs_correction"],
            "overwrite_mgxs_library": False,
            "mgxs_path": "mgxs.h5",
            "runs_openmc": True,
            "why": ("stochastic_slab so every material (notably the copper magnets) gets cross sections regardless of where forward particles "
                    "score; material_wise is available via --mgxs-method but gives empty data behind the shield. The multigroup library only sets "
                    "weight-window efficiency; the continuous-energy run that is compared stays unbiased whatever the windows are."),
        },
        "group_structure_notes": {"cut_at_fast_flux_ev": FAST_FLUX_LOWER_EV, "source_group": source_group(edges, energy)},
        "source_collapse": ("the 14.1 MeV discrete line stays a Discrete([E], [1]) IndependentSource constrained to the plasma cell (domain constraint, "
                            "isotropic); the multigroup solver bins it into the group above"),
        "convert_to_random_ray": {
            "called": False,
            "why": ("its defaults come from geometry.bounding_box, which here is unbounded (outer void cell), so infinities become +-1 cm and the "
                    "ray source would be a 2 cm box; ray source, distances and ray count are set explicitly"),
            "defaults_it_would_choose_on_this_model": {
                "ray_source_box_cm": {"lower_left": [float(v) for v in probe_box.lower_left], "upper_right": [float(v) for v in probe_box.upper_right]},
                "distance_inactive_cm": probe_rr["distance_inactive"], "distance_active_cm": probe_rr["distance_active"], "particles": probe.settings.particles,
            },
        },
        "weight_window_mesh": ww,
        "peak_mesh": build["extents"],
        "configuration": describe_random_ray(rr_model),
        "parameters_not_tuned": ["rays", "batches", "inactive", "distance_inactive_cm", "distance_active_cm", "mgxs_nparticles", "ww cell size"],
        "risks_to_check_on_first_run": [
            "rays are sampled uniformly in the whole-torus box, about half of which lies outside the torus (void beyond the vacuum surface); check that the solve neither stalls nor warns, or raise the ray count",
            "the objective tallies use cell filters on components whose cells are filled with region universes; check the adjoint source is non-zero in vessel and magnets",
            "ray count versus source regions: ~72k mesh cells subdivide the material domains; check scalar fluxes are finite (the solver aborts on non-finite flux)",
        ],
        "void": void_report(build["parts"]),
        "citations": CITATIONS,
    }


# --------------------------------------------------------------------------
# Running OpenMC

def run_openmc(exe: Path, cwd: Path, threads: int) -> float:
    """Run the solver in cwd; return wall seconds. Fails closed on exit code or lost particles."""
    env = os.environ.copy()
    env["OMP_NUM_THREADS"] = str(threads)
    env.setdefault("OPENBLAS_NUM_THREADS", "1")
    env["PATH"] = str(exe.parent) + os.pathsep + env.get("PATH", "")
    start = time.monotonic()
    with (cwd / "openmc.stdout.log").open("wb") as out, (cwd / "openmc.stderr.log").open("wb") as err:
        code = subprocess.run([str(exe)], cwd=cwd, env=env, stdout=out, stderr=err, check=False).returncode
    wall = time.monotonic() - start
    require(code == 0, f"OpenMC exited {code}; see {cwd}/openmc.stderr.log")
    log = (cwd / "openmc.stdout.log").read_bytes() + b"\n" + (cwd / "openmc.stderr.log").read_bytes()
    require(not re.search(rb"(?i)particle\s+\d+\s+was lost|lost particles?", log), "OpenMC reported lost particles")
    return wall


def cli_params(args) -> dict:
    params = dict(PLAN_DEFAULTS)
    for key in ("mgxs_method", "mgxs_correction", "mgxs_nparticles", "rays", "batches", "inactive"):
        value = getattr(args, key, None)
        if value is not None:
            params[key] = value
    require(params["inactive"] < params["batches"], "inactive batches must be fewer than batches")
    return params


def command_build(args) -> int:
    openmc = import_openmc()
    inp = RT.read_input(Path(args.input).expanduser().resolve(strict=True))
    work = fresh_dir(Path(args.work_dir) / "build")
    build = build_spike(inp, work, openmc)
    adapter, spike = xml_hashes(build["adapter_dir"]), xml_hashes(build["spike_dir"])
    report = {
        "schema_version": SCHEMA, "kind": "build", "input_sha256": sha256(Path(args.input)),
        "adapter_xml_sha256": adapter, "spike_xml_sha256": spike,
        "unchanged_from_adapter": sorted(k for k in spike if adapter.get(k) == spike[k]),
        "differs_from_adapter": sorted(k for k in spike if adapter.get(k) != spike[k]),
        "differs_why": {"tallies.xml": "spike tallies replace the adapter's responses", "settings.xml": "photon transport off, per-batch statepoints off"},
        "peak_mesh": build["extents"], "tallies": build["tally_names"], "void": void_report(build["parts"]),
        "spectrum_groups": 709, "spectrum_bounds_source": str(ACTINV_709G),
    }
    (work / "build-report.json").write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0


def command_plan(args) -> int:
    openmc = import_openmc()
    inp = RT.read_input(Path(args.input).expanduser().resolve(strict=True))
    work = fresh_dir(Path(args.work_dir) / "plan")
    build = build_spike(inp, work / "build", openmc)
    plan = plan_document(build["inp"], build, cli_params(args), openmc)
    plan["input_sha256"] = sha256(Path(args.input))
    (work / "mgxs-plan.json").write_text(json.dumps(plan, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(plan, indent=2, sort_keys=True))
    return 0


def command_generate(args) -> int:
    require(args.i_have_the_cpu, "generate runs MGXS generation and a random-ray solve on many cores; pass --i-have-the-cpu to run it")
    openmc = import_openmc()
    input_path = Path(args.input).expanduser().resolve(strict=True)
    inp = RT.read_input(input_path)
    exe = Path(inp["openmc_executable"]).expanduser().resolve(strict=True)
    params = cli_params(args)
    work = fresh_dir(Path(args.work_dir) / "generate")
    build = build_spike(inp, work / "build", openmc)
    inp = build["inp"]
    edges = RR_GROUP_EDGES_EV
    ww = ww_mesh_extents(inp["manifest"], build["variant"])
    ww_mesh = regular_mesh(openmc, ww, "fw-cadis-ww-mesh")
    ray_box = ([100.0 * v for v in ww["lower_left_m"]], [100.0 * v for v in ww["upper_right_m"]])
    model = build["model"]
    run_dir = work / "rr"
    run_dir.mkdir()
    # Multigroup conversion runs OpenMC (continuous energy, neutron only) in a temporary directory.
    os.environ["PATH"] = str(exe.parent) + os.pathsep + os.environ.get("PATH", "")
    os.environ["OMP_NUM_THREADS"] = str(args.threads)
    mgxs_path = run_dir / "mgxs.h5"
    model.convert_to_multigroup(method=params["mgxs_method"], groups=openmc.mgxs.EnergyGroups(edges), nparticles=int(params["mgxs_nparticles"]),
                                overwrite_mgxs_library=False, mgxs_path=str(mgxs_path), correction=params["mgxs_correction"])
    require(mgxs_path.is_file(), "MGXS generation produced no library")
    configure_random_ray(openmc, model, ww_mesh, params, edges, rr_tallies(openmc, build, edges), ray_box, subdivision_domains(model))
    model.export_to_model_xml(path=str(run_dir / "model.xml"))
    wall = run_openmc(exe, run_dir, args.threads)
    ww_file = run_dir / "weight_windows.h5"
    require(ww_file.is_file(), "random-ray run wrote no weight_windows.h5")
    record = {
        "schema_version": SCHEMA, "kind": "generate", "openmc_version": openmc.__version__,
        "input": str(input_path), "input_sha256": sha256(input_path),
        "weight_windows_file": str(ww_file), "weight_windows_sha256": sha256(ww_file),
        "mgxs_sha256": sha256(mgxs_path), "random_ray_wall_seconds": wall,
        "parameters": params, "configuration": describe_random_ray(model),
        "weight_window_mesh": ww, "peak_mesh": build["extents"],
    }
    (work / "generate-record.json").write_text(json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(record, indent=2, sort_keys=True))
    return 0


def read_case(openmc, case_dir: Path, names: list[str], n_batches: int) -> dict:
    """Per-bin mean, relative error, batch values and run time for every spike tally of one run."""
    import numpy as np
    files = {int(p.name.split(".")[1]): p for p in case_dir.glob("statepoint.*.h5")}
    require(sorted(files) == list(range(1, n_batches + 1)), f"{case_dir}: statepoints do not cover batches 1..{n_batches}")
    cumulative = {n: [] for n in names}
    for b in range(1, n_batches + 1):
        with openmc.StatePoint(str(files[b])) as sp:
            require(int(sp.current_batch) == b and int(sp.n_realizations) == b, f"{case_dir}: bad realization count at batch {b}")
            for n in names:
                cumulative[n].append(sp.get_tally(name=n).sum.ravel().copy())
    with openmc.StatePoint(str(files[n_batches])) as sp:
        require(tuple(int(v) for v in sp.version) == (0, 15, 3), "statepoint version is not 0.15.3")
        require(sp.run_mode == "fixed source", "statepoint is not fixed source")
        sim_seconds = sp.runtime.get("simulation")
        require(sim_seconds is not None and sim_seconds > 0, "statepoint carries no simulation run time")
        result = {"simulation_seconds": float(sim_seconds), "histories": int(sp.n_particles) * n_batches, "batches": n_batches, "tallies": {}}
        for n in names:
            tally = sp.get_tally(name=n)
            mean, std = tally.mean.ravel(), tally.std_dev.ravel()
            cum = np.array(cumulative[n])
            per_batch = np.vstack([cum[0], np.diff(cum, axis=0)])
            require(np.allclose(per_batch.mean(axis=0), mean, rtol=1e-9, atol=1e-300), f"{n}: batch values disagree with the statepoint mean")
            with np.errstate(divide="ignore", invalid="ignore"):
                rel = np.where(mean > 0, std / mean, np.nan)
            result["tallies"][n] = {"mean": mean, "rel_err": rel, "vov": variance_of_variance(per_batch)}
    for p in files.values():
        if p.name != f"statepoint.{n_batches}.h5":
            p.unlink(missing_ok=True)
    return result


def summarise(analog: dict, windowed: dict) -> dict:
    import numpy as np

    def stats(entry, seconds):
        mean, rel, vov = entry["mean"], entry["rel_err"], entry["vov"]
        scored = np.isfinite(rel)
        peak = int(np.nanargmax(np.where(scored, mean, np.nan))) if scored.any() else None
        fom = np.where(scored & (rel > 0), 1.0 / (rel ** 2 * seconds), np.nan)
        def q(a, p):
            a = a[np.isfinite(a)]
            return float(np.percentile(a, p)) if a.size else None
        return {"bins": int(mean.size), "bins_scored": int(scored.sum()), "peak_bin": peak,
                "peak_mean": None if peak is None else float(mean[peak]), "peak_rel_err": None if peak is None else float(rel[peak]),
                "peak_vov": None if peak is None else (None if not np.isfinite(vov[peak]) else float(vov[peak])),
                "rel_err_median": q(rel, 50), "rel_err_p90": q(rel, 90), "rel_err_max": q(rel, 100),
                "fraction_rel_err_below_10pct": float((rel[scored] < 0.1).mean()) if scored.any() else None,
                "vov_median": q(vov, 50), "vov_p90": q(vov, 90), "fom_median": q(fom, 50), "fom_peak_bin": None if peak is None else (None if not np.isfinite(fom[peak]) else float(fom[peak]))}

    out = {}
    for name in analog["tallies"]:
        a, w = stats(analog["tallies"][name], analog["simulation_seconds"]), stats(windowed["tallies"][name], windowed["simulation_seconds"])
        ratio = None
        if a["fom_median"] and w["fom_median"]:
            ratio = w["fom_median"] / a["fom_median"]
        out[name] = {"analog": a, "weight_windowed": w, "fom_median_ratio_ww_over_analog": ratio}
    return out


def command_compare(args) -> int:
    require(args.i_have_the_cpu, "compare runs two continuous-energy transport calculations on many cores; pass --i-have-the-cpu to run it")
    import numpy as np
    openmc = import_openmc()
    record_path = Path(args.generate_record).expanduser().resolve(strict=True)
    record = json.loads(record_path.read_text(encoding="utf-8"))
    ww_file = Path(record["weight_windows_file"])
    require(ww_file.is_file() and sha256(ww_file) == record["weight_windows_sha256"], "weight_windows.h5 does not match the hash in the generate record")
    input_path = Path(args.input).expanduser().resolve(strict=True)
    require(sha256(input_path) == record["input_sha256"], "input.json differs from the one the windows were generated for")
    inp = RT.read_input(input_path)
    exe = Path(inp["openmc_executable"]).expanduser().resolve(strict=True)
    work = fresh_dir(Path(args.work_dir) / "compare")
    build = build_spike(inp, work / "build", openmc)
    model = build["model"]
    names = build["tally_names"]
    particles = int(args.particles_per_batch)

    def run_case(label, batches, windows, per_batch):
        case = work / label
        case.mkdir()
        s = model.settings
        s.batches, s.particles, s.seed = int(batches), particles, int(args.seed)
        s.statepoint = {"batches": list(range(1, int(batches) + 1))} if per_batch else {"batches": [int(batches)]}
        s.weight_windows_on = windows
        s.weight_windows_file = str(ww_file) if windows else None
        model.export_to_xml(directory=str(case))
        wall = run_openmc(exe, case, args.threads)
        return case, wall

    case, _ = run_case("analog", args.batches, False, True)
    analog = read_case(openmc, case, names, int(args.batches))
    match = {"mode": args.match, "analog_batches": int(args.batches)}
    ww_batches = int(args.batches)
    if args.match == "wall-time":
        times = {}
        for b in (2, 4):
            pilot, _ = run_case(f"pilot-ww-{b}", b, True, False)
            with openmc.StatePoint(str(pilot / f"statepoint.{b}.h5")) as sp:
                times[b] = float(sp.runtime["simulation"])
        slope = (times[4] - times[2]) / 2.0
        require(slope > 0, "pilot runs gave no positive per-batch time")
        intercept = times[2] - 2.0 * slope
        ww_batches = int(math.floor((analog["simulation_seconds"] - intercept) / slope))
        require(ww_batches >= 10, f"equal-wall-time weight-windowed run would have only {ww_batches} batches; the analog run is too short")
        match.update({"pilot_seconds": times, "seconds_per_batch": slope, "overhead_seconds": intercept})
    match["weight_windowed_batches"] = ww_batches
    case, _ = run_case("weight-windowed", ww_batches, True, True)
    windowed = read_case(openmc, case, names, ww_batches)
    report = {
        "schema_version": SCHEMA, "kind": "compare", "openmc_version": openmc.__version__,
        "input_sha256": record["input_sha256"], "generate_record": str(record_path),
        "weight_windows_sha256": record["weight_windows_sha256"], "generation_parameters": record["parameters"],
        "match": match, "particles_per_batch": particles, "seed": int(args.seed),
        "histories": {"analog": analog["histories"], "weight_windowed": windowed["histories"]},
        "simulation_seconds": {"analog": analog["simulation_seconds"], "weight_windowed": windowed["simulation_seconds"]},
        "summary": summarise(analog, windowed),
        "per_bin": {n: {"analog": {k: np.where(np.isfinite(v), v, np.nan).tolist() for k, v in analog["tallies"][n].items()},
                        "weight_windowed": {k: np.where(np.isfinite(v), v, np.nan).tolist() for k, v in windowed["tallies"][n].items()}} for n in names},
        "note": "FOM = 1 / (relative_error^2 * simulation_seconds) per bin; NaN (JSON null after json.dumps allow_nan) marks bins with no score",
    }
    text = json.dumps(report, indent=2, sort_keys=True, allow_nan=True).replace("NaN", "null")
    (work / "compare-report.json").write_text(text + "\n", encoding="utf-8")
    print(json.dumps({k: report[k] for k in ("match", "histories", "simulation_seconds", "summary")}, indent=2, sort_keys=True).replace("NaN", "null"))
    return 0


def parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="command", required=True)

    def common(sp, plan_options=False):
        sp.add_argument("--input", required=True, type=Path, help="FARIS request input.json (faris-openmc-input/v0.1)")
        sp.add_argument("--work-dir", required=True, type=Path, help="parent directory; the stage writes a fresh subdirectory")
        if plan_options:
            sp.add_argument("--mgxs-method", dest="mgxs_method", choices=("stochastic_slab", "material_wise", "infinite_medium"))
            sp.add_argument("--mgxs-correction", dest="mgxs_correction", choices=("P0",), default=None)
            sp.add_argument("--mgxs-nparticles", dest="mgxs_nparticles", type=int)
            sp.add_argument("--rays", type=int)
            sp.add_argument("--batches", type=int)
            sp.add_argument("--inactive", type=int)

    common(sub.add_parser("build", help="export the adapter and spike models and report the tallies"))
    common(sub.add_parser("mgxs-plan", help="write the planned multigroup/random-ray configuration as JSON; executes nothing"), True)
    g = sub.add_parser("generate", help="MGXS + random ray + weight_windows.h5; heavy")
    common(g, True)
    g.add_argument("--threads", type=int, default=7)
    g.add_argument("--i-have-the-cpu", action="store_true")
    c = sub.add_parser("compare", help="analog vs weight-windowed continuous-energy run; heavy")
    common(c)
    c.add_argument("--generate-record", required=True, type=Path)
    c.add_argument("--match", choices=("histories", "wall-time"), default="histories")
    c.add_argument("--batches", type=int, default=100)
    c.add_argument("--particles-per-batch", type=int, default=100000)
    c.add_argument("--seed", type=int, default=81150011)
    c.add_argument("--threads", type=int, default=7)
    c.add_argument("--i-have-the-cpu", action="store_true")
    return p


def main(argv: list[str] | None = None) -> int:
    args = parser().parse_args(argv)
    try:
        return {"build": command_build, "mgxs-plan": command_plan, "generate": command_generate, "compare": command_compare}[args.command](args)
    except RuntimeError as error:
        print(f"FAIL: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
