#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Generate and check the requirement-to-test trace (requirement QA-002).

A test declares the requirements it verifies with a marker comment directly
above or inside it:

    // Verifies: UNC-002, VAL-061        (Rust)
    # Verifies: ACT-030                  (Python)

The script reads every requirement table in docs/requirements/, collects the
markers from the source tree and writes docs/requirements/TRACE.md. The trace
is generated, never edited by hand. With --check it rewrites nothing and fails
when a marker names an unknown requirement, when the committed trace is stale,
or when a requirement of an already-passed phase has no test.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REQUIREMENTS = ROOT / "docs" / "requirements"
TRACE = REQUIREMENTS / "TRACE.md"
INDEX = REQUIREMENTS / "README.md"
COUNTS_START, COUNTS_END = "<!-- counts:start -->", "<!-- counts:end -->"
STATUSES = ("Met", "Partial", "Unmeasured", "No")
SOURCE_DIRS = ["crates", "controls", "scripts", "integrations", "validation"]
SOURCE_SUFFIXES = {".rs", ".py"}
ROW = re.compile(r"^\| ([A-Z0-9]+-\d{3}) \|")
CELL_SPLIT = re.compile(r"(?<!\\)\|")
MARKER = re.compile(r"(?://|#)\s*Verifies:\s*(.+)$")
ID = re.compile(r"\b[A-Z][A-Z0-9]*-\d{3}\b")
RUST_FN = re.compile(r"^\s*(?:pub(?:\([^)]*\))?\s+)?(?:async\s+)?fn\s+([A-Za-z0-9_]+)")
PY_FN = re.compile(r"^\s*def\s+([A-Za-z0-9_]+)")
# Phases whose gate has been passed. A requirement of a passed phase must have
# at least one test. Empty until the F1 gate.
PASSED_PHASES: tuple[str, ...] = ()


def read_requirements() -> dict[str, dict]:
    found: dict[str, dict] = {}
    for path in sorted(REQUIREMENTS.glob("[0-9][0-9]-*.md")):
        for line in path.read_text(encoding="utf-8").splitlines():
            match = ROW.match(line)
            if not match:
                continue
            cells = [c.strip() for c in CELL_SPLIT.split(line.strip())[1:-1]]
            if len(cells) != 7:
                raise SystemExit(f"{path.name}: {match.group(1)} has {len(cells)} cells, expected 7")
            rid = match.group(1)
            if rid in found:
                raise SystemExit(f"duplicate requirement {rid} in {path.name} and {found[rid]['file']}")
            phase = re.match(r"F\d", cells[5])
            now = cells[6].split(":")[0].strip()
            if now not in STATUSES:
                raise SystemExit(f"{path.name}: {rid} Now column starts with {now!r}, expected one of {STATUSES}")
            found[rid] = {"file": path.name, "phase": phase.group(0) if phase else "", "now": now}
    return found


def read_markers() -> tuple[dict[str, list[str]], list[str]]:
    trace: dict[str, list[str]] = {}
    unknown_context: list[str] = []
    for top in SOURCE_DIRS:
        for path in sorted((ROOT / top).rglob("*")):
            if path.suffix not in SOURCE_SUFFIXES or "target" in path.parts or "__pycache__" in path.parts:
                continue
            if path.resolve() == Path(__file__).resolve():
                continue
            lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
            fn_pattern = RUST_FN if path.suffix == ".rs" else PY_FN
            for index, line in enumerate(lines):
                marker = MARKER.search(line)
                if not marker:
                    continue
                ids = ID.findall(marker.group(1))
                if not ids:
                    unknown_context.append(f"{path.relative_to(ROOT)}:{index + 1}: marker names no requirement ID")
                    continue
                name = None
                for following in lines[index:index + 12]:
                    fn = fn_pattern.match(following)
                    if fn:
                        name = fn.group(1)
                        break
                if name is None:
                    for previous in reversed(lines[max(0, index - 40):index]):
                        fn = fn_pattern.match(previous)
                        if fn:
                            name = fn.group(1)
                            break
                where = f"{path.relative_to(ROOT)}::{name or f'line {index + 1}'}"
                for rid in ids:
                    trace.setdefault(rid, []).append(where)
    return trace, unknown_context


def render(requirements: dict[str, dict], trace: dict[str, list[str]]) -> str:
    traced = [rid for rid in requirements if rid in trace]
    by_file: dict[str, list[str]] = {}
    for rid, info in requirements.items():
        by_file.setdefault(info["file"], []).append(rid)
    lines = [
        "# Requirement-to-test trace",
        "",
        "Generated by `scripts/requirement_trace.py`; do not edit by hand. A test",
        "declares what it verifies with a `Verifies: ID` comment. A traced",
        "requirement has at least one test; whether that test passes is decided by",
        "CI, and whether the requirement's target is fully met is the requirement's",
        "own Now column.",
        "",
        f"Traced: {len(traced)} of {len(requirements)} requirements.",
        "",
        "| File | Requirements | Traced |",
        "| --- | ---: | ---: |",
    ]
    for name, ids in by_file.items():
        lines.append(f"| [{name}]({name}) | {len(ids)} | {sum(1 for r in ids if r in trace)} |")
    lines += ["", "## Traced requirements", "", "| ID | Phase | Tests |", "| --- | --- | --- |"]
    for rid in sorted(traced, key=lambda r: (requirements[r]["file"], r)):
        tests = "<br>".join(f"`{t}`" for t in sorted(set(trace[rid])))
        lines.append(f"| {rid} | {requirements[rid]['phase']} | {tests} |")
    return "\n".join(lines) + "\n"


def render_counts(requirements: dict[str, dict]) -> str:
    """The index's per-file status table, generated so it cannot drift."""
    by_file: dict[str, list[str]] = {}
    for rid, info in requirements.items():
        by_file.setdefault(info["file"], []).append(rid)
    lines = [
        COUNTS_START,
        "| File | Prefixes | Requirements | Met | Partial | Unmeasured | No |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    totals = dict.fromkeys(STATUSES, 0)
    for name in sorted(by_file):
        ids = by_file[name]
        title = (REQUIREMENTS / name).read_text(encoding="utf-8").splitlines()[0].removeprefix("# ").strip()
        prefixes = ", ".join(dict.fromkeys(rid.rsplit("-", 1)[0] for rid in ids))
        counts = {status: sum(1 for r in ids if requirements[r]["now"] == status) for status in STATUSES}
        for status in STATUSES:
            totals[status] += counts[status]
        lines.append(f"| [{title}]({name}) | {prefixes} | {len(ids)} | "
                     + " | ".join(str(counts[s]) for s in STATUSES) + " |")
    lines.append(f"| **Total** | | **{len(requirements)}** | "
                 + " | ".join(f"**{totals[s]}**" for s in STATUSES) + " |")
    lines += [
        "",
        f"Counts are generated from the tables by `scripts/requirement_trace.py`. {totals['Met']} of "
        f"{len(requirements)} requirements are met today; that is the point of the set. It describes where "
        "FARIS is going, not where it is.",
        COUNTS_END,
    ]
    return "\n".join(lines)


def with_counts(index_text: str, counts: str) -> str:
    start, end = index_text.index(COUNTS_START), index_text.index(COUNTS_END) + len(COUNTS_END)
    return index_text[:start] + counts + index_text[end:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="verify instead of writing")
    args = parser.parse_args()
    requirements = read_requirements()
    trace, problems = read_markers()
    problems += [f"marker names unknown requirement {rid} in {', '.join(where)}" for rid, where in trace.items() if rid not in requirements]
    trace = {rid: where for rid, where in trace.items() if rid in requirements}
    problems += [
        f"{rid} belongs to passed phase {info['phase']} but has no test"
        for rid, info in requirements.items()
        if info["phase"] in PASSED_PHASES and rid not in trace
    ]
    text = render(requirements, trace)
    index_text = INDEX.read_text(encoding="utf-8")
    index_new = with_counts(index_text, render_counts(requirements))
    if args.check:
        if not TRACE.exists() or TRACE.read_text(encoding="utf-8") != text:
            problems.append("docs/requirements/TRACE.md is stale; run scripts/requirement_trace.py")
        if index_new != index_text:
            problems.append("docs/requirements/README.md status counts are stale; run scripts/requirement_trace.py")
    else:
        TRACE.write_text(text, encoding="utf-8")
        INDEX.write_text(index_new, encoding="utf-8")
    for problem in problems:
        print(problem, file=sys.stderr)
    print(f"{len(trace)} of {len(requirements)} requirements traced", file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
